spring.application.name=UserAuthService

#defining db details
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=JDBC:mysql://localhost:3306/user_auth_service
spring.datasource.username=point_break
#spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
